from __future__ import annotations

import json
import math
import os
import re
import time
import urllib.error
import urllib.request as urllib_request
from dataclasses import dataclass, field
from typing import Any, Protocol


@dataclass(frozen=True)
class RuntimeMetrics:
    latency_ms: int
    token_usage: int
    subcall_count: int
    recursion_depth: int


@dataclass(frozen=True)
class RuntimeTaskRequest:
    task_id: str
    function_node_id: str
    function_name: str
    batch_index: int
    attempt: int
    reason: str
    context: dict[str, Any]
    mode: str = "translate"


@dataclass(frozen=True)
class RuntimeTaskResult:
    task_id: str
    function_node_id: str
    function_name: str
    success: bool
    translated_artifact: str
    interface_changes: tuple[dict[str, Any], ...]
    diagnostics: tuple[str, ...]
    metrics: RuntimeMetrics
    raw_response: dict[str, Any] = field(default_factory=dict)


class Runtime(Protocol):
    provider: str

    def run(self, request: RuntimeTaskRequest) -> RuntimeTaskResult:
        raise NotImplementedError


def _estimate_tokens(context: dict[str, Any]) -> int:
    text = json.dumps(context, sort_keys=True)
    return max(32, int(math.ceil(len(text) / 4.0)))


def _extract_json_object(text: str) -> dict[str, Any] | None:
    text = text.strip()
    if not text:
        return None

    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass

    fenced_match = re.search(r"```(?:json)?\s*(\{.*\})\s*```", text, re.DOTALL)
    if fenced_match:
        snippet = fenced_match.group(1)
        try:
            parsed = json.loads(snippet)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass

    left = text.find("{")
    right = text.rfind("}")
    if left < 0 or right < 0 or right <= left:
        return None

    snippet = text[left : right + 1]
    try:
        parsed = json.loads(snippet)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


def _coerce_message_content(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        text_chunks: list[str] = []
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                text_chunks.append(str(item.get("text", "")))
        return "\n".join(chunk for chunk in text_chunks if chunk)
    return ""


class MockRuntime:
    def __init__(
        self,
        change_rules: dict[str, list[dict[str, Any]]] | None = None,
        fail_first_attempt_for: set[str] | None = None,
    ) -> None:
        self._change_rules = change_rules or {}
        self._fail_first_attempt_for = fail_first_attempt_for or set()
        self.provider = "mock"

    def run(self, request: RuntimeTaskRequest) -> RuntimeTaskResult:
        start = time.perf_counter()

        should_fail = (
            request.function_name in self._fail_first_attempt_for
            and request.attempt == 1
            and request.mode == "translate"
        )

        context_tokens = _estimate_tokens(request.context)
        subcall_count = max(1, len(request.context.get("immediate_dependencies", [])))
        recursion_depth = max(1, int(request.context.get("depth_hint", 1)))

        if should_fail:
            elapsed_ms = int((time.perf_counter() - start) * 1000)
            return RuntimeTaskResult(
                task_id=request.task_id,
                function_node_id=request.function_node_id,
                function_name=request.function_name,
                success=False,
                translated_artifact="",
                interface_changes=(),
                diagnostics=(
                    f"Simulated deterministic failure for `{request.function_name}` on attempt 1",
                ),
                metrics=RuntimeMetrics(
                    latency_ms=max(1, elapsed_ms),
                    token_usage=context_tokens,
                    subcall_count=subcall_count,
                    recursion_depth=recursion_depth,
                ),
                raw_response={"runtime": "mock", "status": "failed"},
            )

        interface_changes = tuple(self._change_rules.get(request.function_name, []))
        rust_stub = (
            "// Mock translated output\n"
            f"// Source function: {request.function_name}\n"
            f"pub fn {request.function_name}(/* inferred args */) {{\n"
            "    // placeholder generated by MockRuntime\n"
            "}\n"
        )

        elapsed_ms = int((time.perf_counter() - start) * 1000)
        return RuntimeTaskResult(
            task_id=request.task_id,
            function_node_id=request.function_node_id,
            function_name=request.function_name,
            success=True,
            translated_artifact=rust_stub,
            interface_changes=interface_changes,
            diagnostics=(
                f"Mock translation completed for `{request.function_name}`",
                f"Mode: {request.mode}",
            ),
            metrics=RuntimeMetrics(
                latency_ms=max(1, elapsed_ms),
                token_usage=context_tokens,
                subcall_count=subcall_count,
                recursion_depth=recursion_depth,
            ),
            raw_response={
                "runtime": "mock",
                "status": "ok",
                "interface_change_count": len(interface_changes),
            },
        )


class LLMRuntime:
    _DEFAULT_MODEL_BY_PROVIDER = {
        "groq": "llama-3.3-70b-versatile",
        "ollama": "llama3.1",
    }
    _DEFAULT_BASE_URL_BY_PROVIDER = {
        "groq": "https://api.groq.com/openai/v1",
        "ollama": "http://localhost:11434/v1",
    }

    def __init__(
        self,
        *,
        provider: str = "groq",
        model_name: str | None = None,
        base_url: str | None = None,
        api_key: str | None = None,
        timeout_sec: int = 120,
    ) -> None:
        provider_key = provider.strip().lower()
        if provider_key not in self._DEFAULT_MODEL_BY_PROVIDER:
            raise ValueError(f"Unsupported LLM provider: {provider}")

        self.provider = provider_key
        self.model_name = model_name or self._DEFAULT_MODEL_BY_PROVIDER[provider_key]
        self.base_url = base_url or self._DEFAULT_BASE_URL_BY_PROVIDER[provider_key]
        self.timeout_sec = max(1, int(timeout_sec))

        resolved_api_key = api_key
        if resolved_api_key is None:
            env_key = "GROQ_API_KEY" if provider_key == "groq" else "OLLAMA_API_KEY"
            resolved_api_key = os.getenv(env_key)
        self._api_key = (resolved_api_key or "").strip()

        if self.provider == "groq" and not self._api_key:
            raise RuntimeError(
                "Groq runtime requested but no API key was found. "
                "Set GROQ_API_KEY or pass --llm-api-key."
            )

    def run(self, request: RuntimeTaskRequest) -> RuntimeTaskResult:
        start = time.perf_counter()
        prompt = self._build_prompt(request)
        payload = {
            "model": self.model_name,
            "temperature": 0,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are a code migration agent. "
                        "Return ONLY valid JSON and no markdown."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
        }

        body = json.dumps(payload).encode("utf-8")
        headers = {"Content-Type": "application/json"}
        if self._api_key:
            headers["Authorization"] = f"Bearer {self._api_key}"

        endpoint = self.base_url.rstrip("/") + "/chat/completions"
        request_obj = urllib_request.Request(
            endpoint,
            data=body,
            headers=headers,
            method="POST",
        )

        response_payload: dict[str, Any] = {}
        response_text = ""
        diagnostics: list[str] = []
        success = False
        translated_artifact = ""
        interface_changes: tuple[dict[str, Any], ...] = ()

        try:
            with urllib_request.urlopen(
                request_obj, timeout=self.timeout_sec
            ) as response:
                response_text = response.read().decode("utf-8", errors="replace")
        except urllib.error.HTTPError as exc:
            body_text = exc.read().decode("utf-8", errors="replace")
            diagnostics.append(
                f"LLM HTTP error {exc.code} for `{request.function_name}`: {body_text}"
            )
            return self._failure_result(
                request=request,
                start=start,
                diagnostics=diagnostics,
                response_text=body_text,
            )
        except urllib.error.URLError as exc:
            diagnostics.append(
                f"LLM connection error for `{request.function_name}`: {exc.reason}"
            )
            return self._failure_result(
                request=request,
                start=start,
                diagnostics=diagnostics,
                response_text="",
            )

        try:
            response_payload = json.loads(response_text) if response_text else {}
        except json.JSONDecodeError:
            diagnostics.append("LLM response was not valid JSON")
            return self._failure_result(
                request=request,
                start=start,
                diagnostics=diagnostics,
                response_text=response_text,
            )

        message_content = ""
        choices = response_payload.get("choices", [])
        if isinstance(choices, list) and choices:
            first_choice = choices[0]
            if isinstance(first_choice, dict):
                message = first_choice.get("message", {})
                if isinstance(message, dict):
                    message_content = _coerce_message_content(message.get("content"))

        parsed = _extract_json_object(message_content) or {}
        if not parsed:
            diagnostics.append("LLM output did not contain a valid JSON object")

        interface_changes_raw = parsed.get("interface_changes", [])
        if not isinstance(interface_changes_raw, list):
            interface_changes_raw = []
        interface_changes = tuple(
            item for item in interface_changes_raw if isinstance(item, dict)
        )

        diagnostics_raw = parsed.get("diagnostics", [])
        if isinstance(diagnostics_raw, list):
            diagnostics.extend(str(item) for item in diagnostics_raw)

        translated_artifact = str(parsed.get("translated_artifact", "")).strip()
        success = bool(parsed.get("success", bool(translated_artifact and parsed)))

        usage = response_payload.get("usage", {})
        token_usage = _estimate_tokens(request.context)
        if isinstance(usage, dict):
            total_tokens = usage.get("total_tokens")
            if isinstance(total_tokens, int) and total_tokens > 0:
                token_usage = total_tokens

        latency_ms = int((time.perf_counter() - start) * 1000)
        subcall_count = 1
        recursion_depth = max(1, int(request.context.get("depth_hint", 1)))

        return RuntimeTaskResult(
            task_id=request.task_id,
            function_node_id=request.function_node_id,
            function_name=request.function_name,
            success=success,
            translated_artifact=translated_artifact,
            interface_changes=interface_changes,
            diagnostics=tuple(diagnostics),
            metrics=RuntimeMetrics(
                latency_ms=max(1, latency_ms),
                token_usage=max(1, token_usage),
                subcall_count=subcall_count,
                recursion_depth=recursion_depth,
            ),
            raw_response={
                "provider": self.provider,
                "model": self.model_name,
                "message_content": message_content,
                "parsed": parsed,
                "usage": usage,
            },
        )

    def _failure_result(
        self,
        *,
        request: RuntimeTaskRequest,
        start: float,
        diagnostics: list[str],
        response_text: str,
    ) -> RuntimeTaskResult:
        latency_ms = int((time.perf_counter() - start) * 1000)
        token_usage = _estimate_tokens(request.context)
        return RuntimeTaskResult(
            task_id=request.task_id,
            function_node_id=request.function_node_id,
            function_name=request.function_name,
            success=False,
            translated_artifact="",
            interface_changes=(),
            diagnostics=tuple(diagnostics),
            metrics=RuntimeMetrics(
                latency_ms=max(1, latency_ms),
                token_usage=max(1, token_usage),
                subcall_count=1,
                recursion_depth=max(1, int(request.context.get("depth_hint", 1))),
            ),
            raw_response={
                "provider": self.provider,
                "model": self.model_name,
                "response": response_text,
            },
        )

    @staticmethod
    def _build_prompt(request: RuntimeTaskRequest) -> str:
        payload = {
            "task_id": request.task_id,
            "function_node_id": request.function_node_id,
            "function_name": request.function_name,
            "batch_index": request.batch_index,
            "attempt": request.attempt,
            "reason": request.reason,
            "mode": request.mode,
            "context": request.context,
        }
        return (
            "Return ONLY valid JSON with keys: "
            "success (bool), translated_artifact (string), "
            "interface_changes (list of change events), diagnostics (list of strings)."
            "\n\nINPUT:\n" + json.dumps(payload, indent=2, sort_keys=True)
        )


def build_runtime(
    runtime_name: str,
    *,
    change_rules: dict[str, list[dict[str, Any]]] | None = None,
    fail_first_attempt_for: set[str] | None = None,
    llm_provider: str = "groq",
    llm_model: str | None = None,
    llm_base_url: str | None = None,
    llm_api_key: str | None = None,
    timeout_sec: int = 120,
) -> Runtime:
    name = runtime_name.strip().lower()
    if name == "mock":
        return MockRuntime(
            change_rules=change_rules,
            fail_first_attempt_for=fail_first_attempt_for,
        )
    if name == "llm":
        return LLMRuntime(
            provider=llm_provider,
            model_name=llm_model,
            base_url=llm_base_url,
            api_key=llm_api_key,
            timeout_sec=timeout_sec,
        )
    raise ValueError(f"Unsupported runtime: {runtime_name}")
