from __future__ import annotations

import json
import math
import time
from dataclasses import dataclass, field
from typing import Any, Protocol


@dataclass(frozen=True)
class RuntimeMetrics:
    latency_ms: int
    token_usage: int
    subcall_count: int
    recursion_depth: int


@dataclass(frozen=True)
class RuntimeTaskRequest:
    task_id: str
    function_node_id: str
    function_name: str
    batch_index: int
    attempt: int
    reason: str
    context: dict[str, Any]
    mode: str = "translate"


@dataclass(frozen=True)
class RuntimeTaskResult:
    task_id: str
    function_node_id: str
    function_name: str
    success: bool
    translated_artifact: str
    interface_changes: tuple[dict[str, Any], ...]
    diagnostics: tuple[str, ...]
    metrics: RuntimeMetrics
    raw_response: dict[str, Any] = field(default_factory=dict)


class Runtime(Protocol):
    def run(self, request: RuntimeTaskRequest) -> RuntimeTaskResult:
        raise NotImplementedError


def _estimate_tokens(context: dict[str, Any]) -> int:
    text = json.dumps(context, sort_keys=True)
    return max(32, int(math.ceil(len(text) / 4.0)))


class MockRuntime:
    """
    Deterministic offline runtime.

    The mock runtime does not call external language models. It produces
    structured outputs from local rules so orchestration logic can be tested
    without API keys or network access.
    """

    def __init__(
        self,
        change_rules: dict[str, list[dict[str, Any]]] | None = None,
        fail_first_attempt_for: set[str] | None = None,
    ) -> None:
        self._change_rules = change_rules or {}
        self._fail_first_attempt_for = fail_first_attempt_for or set()

    def run(self, request: RuntimeTaskRequest) -> RuntimeTaskResult:
        start = time.perf_counter()

        should_fail = (
            request.function_name in self._fail_first_attempt_for
            and request.attempt == 1
            and request.mode == "translate"
        )

        context_tokens = _estimate_tokens(request.context)
        subcall_count = max(1, len(request.context.get("immediate_dependencies", [])))
        depth_hint = request.context.get("depth_hint", 1)
        recursion_depth = max(1, int(depth_hint))

        if should_fail:
            elapsed_ms = int((time.perf_counter() - start) * 1000)
            return RuntimeTaskResult(
                task_id=request.task_id,
                function_node_id=request.function_node_id,
                function_name=request.function_name,
                success=False,
                translated_artifact="",
                interface_changes=(),
                diagnostics=(
                    f"Simulated deterministic failure for `{request.function_name}` on attempt 1",
                ),
                metrics=RuntimeMetrics(
                    latency_ms=max(1, elapsed_ms),
                    token_usage=context_tokens,
                    subcall_count=subcall_count,
                    recursion_depth=recursion_depth,
                ),
                raw_response={"runtime": "mock", "status": "failed"},
            )

        interface_changes = tuple(self._change_rules.get(request.function_name, []))
        rust_stub = (
            f"// Mock translated output\n"
            f"// Source function: {request.function_name}\n"
            f"pub fn {request.function_name}(/* inferred args */) {{\n"
            f"    // placeholder generated by MockRuntime\n"
            f"}}\n"
        )

        elapsed_ms = int((time.perf_counter() - start) * 1000)
        return RuntimeTaskResult(
            task_id=request.task_id,
            function_node_id=request.function_node_id,
            function_name=request.function_name,
            success=True,
            translated_artifact=rust_stub,
            interface_changes=interface_changes,
            diagnostics=(
                f"Mock translation completed for `{request.function_name}`",
                f"Mode: {request.mode}",
            ),
            metrics=RuntimeMetrics(
                latency_ms=max(1, elapsed_ms),
                token_usage=context_tokens,
                subcall_count=subcall_count,
                recursion_depth=recursion_depth,
            ),
            raw_response={
                "runtime": "mock",
                "status": "ok",
                "interface_change_count": len(interface_changes),
            },
        )


def _extract_json_object(text: str) -> dict[str, Any] | None:
    text = text.strip()
    if not text:
        return None
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass

    left = text.find("{")
    right = text.rfind("}")
    if left < 0 or right < 0 or right <= left:
        return None
    snippet = text[left : right + 1]
    try:
        parsed = json.loads(snippet)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


class RLMRuntime:
    """
    Optional adapter for `alexzhang13/rlm`.

    This adapter is intentionally lightweight. If the `rlm` package is not
    available, initialization fails with a clear error.
    """

    def __init__(
        self,
        backend: str = "openai",
        backend_kwargs: dict[str, Any] | None = None,
        environment: str = "local",
        environment_kwargs: dict[str, Any] | None = None,
        verbose: bool = False,
    ) -> None:
        try:
            from rlm import RLM  # type: ignore
        except Exception as exc:  # pragma: no cover - optional dependency
            raise RuntimeError(
                "RLM runtime requested but package `rlm` is not available. "
                "Install with `pip install rlms` (or the compatible rlm package)."
            ) from exc

        backend_kwargs = backend_kwargs or {}
        environment_kwargs = environment_kwargs or {}

        self._client = RLM(
            backend=backend,
            backend_kwargs=backend_kwargs,
            environment=environment,
            environment_kwargs=environment_kwargs,
            verbose=verbose,
        )

    def run(self, request: RuntimeTaskRequest) -> RuntimeTaskResult:
        start = time.perf_counter()
        prompt = self._build_prompt(request)

        completion = self._client.completion(prompt)
        response_text = str(getattr(completion, "response", ""))
        parsed = _extract_json_object(response_text) or {}

        interface_changes_raw = parsed.get("interface_changes", [])
        if not isinstance(interface_changes_raw, list):
            interface_changes_raw = []
        interface_changes: tuple[dict[str, Any], ...] = tuple(
            item for item in interface_changes_raw if isinstance(item, dict)
        )

        diagnostics_raw = parsed.get("diagnostics", [])
        if not isinstance(diagnostics_raw, list):
            diagnostics_raw = []
        diagnostics = tuple(str(item) for item in diagnostics_raw)

        translated_artifact = str(parsed.get("translated_artifact", "")).strip()
        success = bool(parsed.get("success", bool(translated_artifact)))

        metadata = getattr(completion, "metadata", None)
        latency_ms = int((time.perf_counter() - start) * 1000)
        token_usage = _estimate_tokens(request.context)
        subcall_count = 1
        recursion_depth = max(1, int(request.context.get("depth_hint", 1)))

        if isinstance(metadata, dict):
            token_usage = int(metadata.get("token_usage", token_usage))
            subcall_count = int(metadata.get("subcall_count", subcall_count))
            recursion_depth = int(metadata.get("recursion_depth", recursion_depth))

        return RuntimeTaskResult(
            task_id=request.task_id,
            function_node_id=request.function_node_id,
            function_name=request.function_name,
            success=success,
            translated_artifact=translated_artifact,
            interface_changes=interface_changes,
            diagnostics=diagnostics,
            metrics=RuntimeMetrics(
                latency_ms=max(1, latency_ms),
                token_usage=max(1, token_usage),
                subcall_count=max(1, subcall_count),
                recursion_depth=max(1, recursion_depth),
            ),
            raw_response={
                "response": response_text,
                "parsed": parsed,
                "metadata": metadata,
            },
        )

    @staticmethod
    def _build_prompt(request: RuntimeTaskRequest) -> str:
        payload = {
            "task_id": request.task_id,
            "function_node_id": request.function_node_id,
            "function_name": request.function_name,
            "batch_index": request.batch_index,
            "attempt": request.attempt,
            "reason": request.reason,
            "mode": request.mode,
            "context": request.context,
        }
        return (
            "You are a migration sub-agent."
            " Return ONLY valid JSON with keys:"
            " success (bool), translated_artifact (string),"
            " interface_changes (list of change events), diagnostics (list of strings)."
            "\n\nINPUT:\n" + json.dumps(payload, indent=2, sort_keys=True)
        )


def build_runtime(
    runtime_name: str,
    *,
    change_rules: dict[str, list[dict[str, Any]]] | None = None,
    fail_first_attempt_for: set[str] | None = None,
    backend: str = "openai",
    backend_kwargs: dict[str, Any] | None = None,
    environment: str = "local",
    environment_kwargs: dict[str, Any] | None = None,
    verbose: bool = False,
) -> Runtime:
    name = runtime_name.strip().lower()
    if name == "mock":
        return MockRuntime(
            change_rules=change_rules,
            fail_first_attempt_for=fail_first_attempt_for,
        )
    if name == "rlm":
        return RLMRuntime(
            backend=backend,
            backend_kwargs=backend_kwargs,
            environment=environment,
            environment_kwargs=environment_kwargs,
            verbose=verbose,
        )
    raise ValueError(f"Unsupported runtime: {runtime_name}")
